name: Sync to Hugging Face Hub
on:
  push:
    branches: [jyotsna_version_batch_processing]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://jshug:$HF_TOKEN@huggingface.co/spaces/jshug/meta-hackathon-new HEAD:main
